## 2. Creating Arrays

In [1]:
import numpy as np

In [2]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [3]:
sample_array.dtype

dtype('int64')

In [4]:
ones = np.ones((2, 3), dtype=int)

In [5]:
ones.dtype

dtype('int64')

In [6]:
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [7]:
zeros = np.zeros((2, 3), dtype=int)

In [8]:
zeros.dtype

dtype('int64')

In [9]:
zeros

array([[0, 0, 0],
       [0, 0, 0]])

In [10]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [11]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[2, 3, 6, 3, 3],
       [4, 5, 6, 7, 8],
       [3, 6, 8, 0, 5]])

In [12]:
random_array.size

15

In [13]:
random_array.shape

(3, 5)

In [14]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.70681284, 0.64454361, 0.28214647],
       [0.03793133, 0.82194208, 0.30646577],
       [0.69042882, 0.65678219, 0.33161187],
       [0.12604903, 0.28442015, 0.37208987],
       [0.34261408, 0.40956196, 0.20406123]])

In [15]:
random_array_2.shape

(5, 3)

In [16]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.69283722, 0.65868287, 0.48129665],
       [0.49275633, 0.85168254, 0.3498568 ],
       [0.97796981, 0.48404244, 0.38006145],
       [0.82100864, 0.44870689, 0.24770501],
       [0.12057416, 0.3503851 , 0.19352679]])

In [29]:
# Pseudo-random numbers
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [44]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [45]:
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])