## 2. Creating Arrays

In [1]:
import numpy as np

In [2]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [3]:
sample_array.dtype

dtype('int64')

In [4]:
ones = np.ones((2, 3), dtype=int)

In [5]:
ones.dtype

dtype('int64')

In [6]:
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [7]:
zeros = np.zeros((2, 3), dtype=int)

In [8]:
zeros.dtype

dtype('int64')

In [9]:
zeros

array([[0, 0, 0],
       [0, 0, 0]])

In [10]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [11]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[6, 6, 6, 8, 1],
       [7, 4, 0, 9, 0],
       [4, 1, 3, 2, 2]])

In [12]:
random_array.size

15

In [13]:
random_array.shape

(3, 5)

In [14]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.82749672, 0.66097715, 0.28598271],
       [0.76116148, 0.87413495, 0.90178137],
       [0.02350216, 0.59486011, 0.30788196],
       [0.16216614, 0.16089401, 0.18150577],
       [0.22427352, 0.49442981, 0.90406771]])

In [15]:
random_array_2.shape

(5, 3)

In [16]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.47716644, 0.17293101, 0.49100462],
       [0.80095152, 0.2156079 , 0.19605166],
       [0.70456115, 0.72115628, 0.33887083],
       [0.16682046, 0.06612255, 0.30078706],
       [0.53886059, 0.24643268, 0.64603811]])

In [ ]:
# Pseudo-random numbers
np.random.seed()