## 3. Viewing array and matrices

In [1]:
import numpy as np

In [2]:
# Pseudo-random numbers
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [3]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [5]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a2[1]

array([4. , 5. , 6.5])

In [7]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6]],
               [[7, 8, 9],
                [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [8]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [9]:
np.random.seed(1)
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[5, 8, 9, 5, 0],
         [0, 1, 7, 6, 9],
         [2, 4, 5, 2, 4],
         [2, 4, 7, 7, 9]],

        [[1, 7, 0, 6, 9],
         [9, 7, 6, 9, 1],
         [0, 1, 8, 8, 3],
         [9, 8, 7, 3, 6]],

        [[5, 1, 9, 3, 4],
         [8, 1, 4, 0, 3],
         [9, 2, 0, 4, 9],
         [2, 7, 7, 9, 8]]],


       [[[6, 9, 3, 7, 7],
         [4, 5, 9, 3, 6],
         [8, 0, 2, 7, 7],
         [9, 7, 3, 0, 8]],

        [[7, 7, 1, 1, 3],
         [0, 8, 6, 4, 5],
         [6, 2, 5, 7, 8],
         [4, 4, 7, 7, 4]],

        [[9, 0, 2, 0, 7],
         [1, 7, 9, 8, 4],
         [0, 1, 9, 8, 2],
         [3, 1, 2, 7, 2]]]])

In [10]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [11]:
# Get the first 3 numbers of the inner most array
a4[:, :, :, :3]

array([[[[5, 8, 9],
         [0, 1, 7],
         [2, 4, 5],
         [2, 4, 7]],

        [[1, 7, 0],
         [9, 7, 6],
         [0, 1, 8],
         [9, 8, 7]],

        [[5, 1, 9],
         [8, 1, 4],
         [9, 2, 0],
         [2, 7, 7]]],


       [[[6, 9, 3],
         [4, 5, 9],
         [8, 0, 2],
         [9, 7, 3]],

        [[7, 7, 1],
         [0, 8, 6],
         [6, 2, 5],
         [4, 4, 7]],

        [[9, 0, 2],
         [1, 7, 9],
         [0, 1, 9],
         [3, 1, 2]]]])