## 4. Manipulating & comparing arrays

### Arithmetic

In [1]:
import numpy as np

In [2]:
a1 = np.array([1, 2, 3])

a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])
a1

array([1, 2, 3])

In [3]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [4]:
a1 + ones

array([2., 3., 4.])

In [5]:
a1 - ones

array([0., 1., 2.])

In [6]:
a1 * ones

array([1., 2., 3.])

In [7]:
a1

array([1, 2, 3])

In [8]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [9]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [10]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [11]:
# How can you reshape a2 to be compatible with a3
# Search: "How to reshape numpy"
# a2 * a3 # Error

In [12]:
a2 / a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [13]:
# Floor division removes the decimals
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [14]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [15]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [16]:
a1 + 1

array([2, 3, 4])

In [17]:
np.add(a1, ones)

array([2., 3., 4.])

In [18]:
a1 % 2

array([1, 0, 1])

In [19]:
np.mod(a1, 2)

array([1, 0, 1])

In [20]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [21]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])