### Aggregation

Aggregation = performing the same operation on a number of things

In [1]:
import numpy as np

In [2]:
a1 = np.array([1, 2, 3])

a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])
a1

array([1, 2, 3])

In [3]:
listy_list = [1, 2, 3]
type(listy_list)

list

In [4]:
sum(listy_list)

6

In [5]:
sum(a1)

6

In [6]:
np.sum(a1)

6

> Use Python's methods on Python datatypes \
> and use NumPy's methods on NumPy arrays

In [7]:
# Creative a massive NumPy array
np.random.seed(2)
massive_array = np.random.random(100000)
massive_array.size

100000

In [8]:
massive_array[:10]

array([0.4359949 , 0.02592623, 0.54966248, 0.43532239, 0.4203678 ,
       0.33033482, 0.20464863, 0.61927097, 0.29965467, 0.26682728])

In [9]:
%timeit sum(massive_array) # Python's sum()
%timeit np.sum(massive_array) # NumPy's sum()

3.67 ms ± 10.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
20 µs ± 29 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [10]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [11]:
np.mean(a2)

3.6333333333333333

In [12]:
np.max(a2)

6.5

In [13]:
np.min(a2)

1.0

In [14]:
# Standard deviation = a measure of how spread out a group of numbers is from the mean
np.std(a2)

1.8226964152656422

In [15]:
# Variance = measure of the avaerage degree to which each number is different to the mean
# Higher variance = wider range of numbers
# Logher variance = lower range of numbers
np.var(a2)

3.3222222222222224

In [16]:
# Standard deviation = squareroot of variance
np.sqrt(np.var(a2))

1.8226964152656422