### Dot product example (but butter sales)

In [1]:
import numpy as np
import pandas as pd

In [2]:
np.random.seed(0)
# Number of jars sold
sales_amounts = np.random.randint(20, size=(5, 3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [3]:
# Create weekly_sales DataFrame
weekly_sales = pd.DataFrame(sales_amounts,
                            index=["Mon", "Tues", "Wed", "Thurs", "Fri"],
                            columns=["Almont butter", "Peanut butter", "Cashew butter"])
weekly_sales

Almont butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [4]:
weekly_sales.shape

(5, 3)

In [5]:
# Create prices array
prices = np.array([10, 8, 12])
prices

array([10,  8, 12])

In [6]:
prices.shape

(3,)

In [7]:
# Create butter_prices DataFrame
butter_prices = pd.DataFrame(prices.reshape(1, 3),
                            index=["Price"],
                            columns=["Almont butter", "Peanut butter", "Cashew butter"])
butter_prices

Almont butter  Peanut butter  Cashew butter
Price             10              8             12

In [8]:
# total_sales = prices.dot(sales_amount)

In [9]:
sales_amounts.shape, butter_prices.shape

((5, 3), (1, 3))

In [10]:
# Shape aren't aligned, let's transpose
total_sales = prices.dot(sales_amounts.T)
total_sales

array([240, 138, 458, 232, 142])

In [11]:
# Create daily_sales
butter_prices

Almont butter  Peanut butter  Cashew butter
Price             10              8             12

In [12]:
weekly_sales

Almont butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [13]:
butter_prices.shape, weekly_sales.shape

((1, 3), (5, 3))

In [14]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales
# type(daily_sales)

Mon  Tues  Wed  Thurs  Fri
Price  240   138  458    232  142

In [15]:
weekly_sales_total = weekly_sales.copy()
weekly_sales_total

Almont butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [16]:
# weekly_sales["Total ($)"] = daily_sales
weekly_sales_total["Total ($)"] = daily_sales.T
weekly_sales_total

Almont butter  Peanut butter  Cashew butter  Total ($)
Mon               12             15              0        240
Tues               3              3              7        138
Wed                9             19             18        458
Thurs              4              6             12        232
Fri                1              6              7        142