## 5. Sorting arrays

In [1]:
import numpy as np

In [2]:
np.random.seed(0)
random_array = np.random.randint(10, size=(3, 5))
random_array

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1]])

In [3]:
random_array.shape

(3, 5)

In [4]:
np.sort(random_array)

array([[0, 3, 3, 5, 7],
       [2, 3, 4, 5, 9],
       [1, 6, 7, 8, 8]])

In [5]:
np.argsort(random_array)

array([[1, 2, 3, 0, 4],
       [3, 1, 4, 2, 0],
       [4, 1, 0, 2, 3]])

In [6]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [7]:
np.argsort(a1)

array([0, 1, 2])

In [8]:
np.argmin(a1)

0

In [9]:
np.argmax(a1)

2

In [10]:
random_array

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1]])

In [11]:
np.argmax(random_array, axis=0)

array([1, 2, 2, 2, 0])

In [12]:
np.argmax(random_array, axis=1)

array([4, 0, 2])